version: "3.5"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=scheduler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build: .
    image: scheduler-ktor
    container_name: backend
    environment:
      - POSTGRES_DB=scheduler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    restart: always
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - "8080:8080"

volumes:
  postgres:

networks:
  backend:
    name: backend_network